### ISSUE TITLE
Plugin fails to pull dependencies

### ISSUE THREAD

**Issue by trimbleAdam** [hypnoglow/helm-s3#144]
When using chart dependencies such as the following, s3 plugin fails with error.

$ helm dep up
Getting updates for unmanaged Helm repositories..
Error: could not find protocol handler for: s3

The Chart.yaml for chart which used to work in chartmuseum:
```
apiVersion: v2
description: Cool Chart
name: cool-chart
version: 1.0.0
dependencies:
  - name: cool-base
    version: 1.0.6
    repository: s3://the-repo
    alias: cool-chart
type: application
```
