### ISSUE TITLE
helm s3 reindex fails with invalid character when chart comes with semver range in meta data

### ISSUE THREAD

**Issue by josephprem** [hypnoglow/helm-s3#147]
aws-ebs-csi-driver chart below contains kubeVersion: '>=1.17.0-0'  in Chart.yaml .
When the chart is pushed it is automatically indexed correctly, but when I run helm s3 reindex it fails
```bash
helm s3 version --mode
helm-s3 plugin version: 0.10.0
Helm version mode: v3
```

```bash
helm s3 reindex --relative myrepo
traverse the chart repository: unserialize chart meta: invalid character '=' looking for beginning of value
```
cat index.yaml 

```yaml
apiVersion: v1
entries:
  aws-ebs-csi-driver:
  - apiVersion: v1
    appVersion: 0.9.0
    created: "2021-05-03T18:35:40.95243566Z"
    description: A Helm chart for AWS EBS CSI Driver
    digest: 0e30e20dd7e21cacf6066cd7aa2c8331b48faf068c3c9985d877f9845d7982be
    home: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
    keywords:
    - aws
    - ebs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: chengpan@amazon.com
      name: leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-ebs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-ebs-csi-driver
    urls:
    - aws-ebs-csi-driver-0.9.0.tgz
    version: 0.9.0
  efs-provisioner:
  - apiVersion: v1
    appVersion: v2.4.0
    created: "2021-05-03T18:35:43.218370009Z"
    deprecated: true
    description: DEPRECATED A Helm chart for the AWS EFS external storage provisioner
    digest: d99d17cb5811827c87fc4b9e9e6610dcb0c00cfd94539b1e14591a49d9e613e1
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    name: efs-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    - https://github.com/mirror/busybox
    urls:
    - efs-provisioner-0.13.2.tgz
    version: 0.13.2
generated: "2021-04-29T17:47:26.794900189Z"
```
