### ISSUE TITLE
Version number with `+` gets double URL escaped when using relative URLs

### ISSUE THREAD

**Issue by pete-woods** [hypnoglow/helm-s3#242]
e.g. `v0.1.86-alpha+a857d7c` can be seen in the YAML index as:
```yaml
  - apiVersion: v2
    created: "2022-11-24T09:39:55.864130924Z"
    description: Deploy
    digest: 241ab62077ab3ca7f0e173b3400ee11fa3bbcb1b845be2ddf63cc3beb73a6ac3
    name: deploy
    type: library
    urls:
    - deploy-v0.1.86-alpha%2Ba857d7c.tgz
    version: v0.1.86-alpha+a857d7c
```

Then Helm later tries to download from a URL like: `https://...../deploy-v0.1.86-alpha%252Ba857d7c.tgz`, where `%252B` appears to be a doubly escaped `+`.
